### ISSUE TITLE
kodi should be idle when an emulator runs

### ISSUE THREAD

**Issue by leissa** [Wintermute0110/plugin.program.advanced.emulator.launcher#58] opened 2018-01-08 00:24 UTC
Currently, kodi still runs in background when an emulator runs. This costs unnecessary CPU cycles. Sth like
```bash
kill -STOP kodi_pid
run_emulator
kill -CONT kodi_pid
```
should already do the trick.

**Comment by Wintermute0110** [comment] 2018-01-12 06:33
By design Kodi is left running in the background. Yes, this has some CPU cost but experience tells it is the best from the user experience (for example, less delays when returning to Kodi, you return to the ROM you were browsing, etc.).

If you want to kill Kodi and restart it again when you finish the launcher application then you must use an script. You have some examples in the [AEL Asset Library](https://github.com/Wintermute0110/AEL-asset-library/tree/master/Utilities).

**Comment by Wintermute0110** [comment] 2018-01-16 08:14
I will close the issue now. Reopen or open a new one if you find any other problem.

**Closed by Wintermute0110** 2018-01-16 08:14 UTC
