### ISSUE TITLE
Error adding ROMs

### ISSUE THREAD

**Issue by jader9920** [Wintermute0110/plugin.program.advanced.emulator.launcher#18] opened 2016-08-17 16:31 UTC
when attempting to add ROMs for the first time I am getting this error:

11:27:01 T:10860   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.NameError'>
                                            Error Contents: global name 'local_title' is not defined
                                            Traceback (most recent call last):
                                              File "C:\Users\jader\AppData\Roaming\Kodi\addons\plugin.program.advanced.emulator.launcher\addon.py", line 47, in <module>
                                                plugin.run_plugin()
                                              File "C:\Users\jader\AppData\Roaming\Kodi\addons\plugin.program.advanced.emulator.launcher\resources\main.py", line 218, in run_plugin
                                                self._command_add_roms(args['launID'][0])
                                              File "C:\Users\jader\AppData\Roaming\Kodi\addons\plugin.program.advanced.emulator.launcher\resources\main.py", line 1447, in _command_add_roms
                                                self._roms_import_roms(launcher)
                                              File "C:\Users\jader\AppData\Roaming\Kodi\addons\plugin.program.advanced.emulator.launcher\resources\main.py", line 4386, in _roms_import_roms
                                                romdata     = self._roms_process_scanned_ROM(launcherID, ROM)
                                              File "C:\Users\jader\AppData\Roaming\Kodi\addons\plugin.program.advanced.emulator.launcher\resources\main.py", line 4598, in _roms_process_scanned_ROM
                                                selected_title     = self._roms_process_asset_policy_2(ASSET_TITLE, local_title, ROM, launcher)
                                            NameError: global name 'local_title' is not defined
                                            -->End of Python script error report<--

**Comment by jader9920** [comment] 2016-08-17 17:08
UPDATE: Still getting this error after using the latest commit

**Comment by mac1202** [comment] 2016-08-17 17:09
Duplicate of https://github.com/Wintermute0110/plugin.program.advanced.emulator.launcher/issues/13
Disable the online scraper until they are fixed.

**Comment by jader9920** [comment] 2016-08-17 17:30
ROMs are adding, new error same as issue #19

**Comment by Wintermute0110** [comment] 2016-08-17 17:43
This issue should be fixed now.

Keep in mind that scraper does not work on `Edit ROM` and `Edit Launcher` menus for the moment. Also, scraper does not differentiate between different artwork kinds and likely will download the same image always... which is not an issue because there is no skin that displays all AEL artwork... yet.

**Comment by Wintermute0110** [comment] 2016-08-20 13:25
Will close the issue now. Reopen if you find same problem or open a new one if find a new problem.

**Closed by Wintermute0110** 2016-08-20 13:25 UTC
