### ISSUE TITLE
Issues Adding new roms

### ISSUE THREAD

**Issue by eggfoo** [Wintermute0110/plugin.program.advanced.emulator.launcher#8] opened 2016-07-17 19:48 UTC
Ran into an issues when trying to add roms to a launcher.
Kodi v16 Jarvis
Windows 7

I applied the most recent fix for the trailers. I have 2 machines. My family HTPC. And my main PC rig.

I do all of my kodi/AEL testing on the PC rig b4 I move over to the HTPC.

If you need to me record another video let me know.
Thanks.

```
15:42:36 T:19496  NOTICE: AEL INFO : Launcher is empty. No dead ROM check.
15:42:36 T:19496  NOTICE: AEL INFO : Scanning files in F:\Users\New Super Mario Bros. Wii (USA)\
15:42:36 T:19496  NOTICE: AEL INFO : Recursive scan activated
15:42:36 T:19496  NOTICE: AEL INFO : Found 2 files
15:42:36 T:19496   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.ValueError'>
                                            Error Contents: Invalid mode ('rtb')
                                            Traceback (most recent call last):
                                              File "C:\Users\Monki\AppData\Roaming\Kodi\addons\plugin.program.advanced.emulator.launcher-master\addon.py", line 45, in <module>
                                                plugin.run_plugin()
                                              File "C:\Users\Monki\AppData\Roaming\Kodi\addons\plugin.program.advanced.emulator.launcher-master\resources\main.py", line 234, in run_plugin
                                                self._command_add_roms(args['launID'][0])
                                              File "C:\Users\Monki\AppData\Roaming\Kodi\addons\plugin.program.advanced.emulator.launcher-master\resources\main.py", line 1227, in _command_add_roms
                                                self._roms_import_roms(launcher)
                                              File "C:\Users\Monki\AppData\Roaming\Kodi\addons\plugin.program.advanced.emulator.launcher-master\resources\main.py", line 3601, in _roms_import_roms
                                                romdata     = self._roms_process_scanned_ROM(launcherID, ROM)
                                              File "C:\Users\Monki\AppData\Roaming\Kodi\addons\plugin.program.advanced.emulator.launcher-master\resources\main.py", line 3714, in _roms_process_scanned_ROM
                                                nfo_dic = fs_load_NFO_file_scanner(nfo_file_path)
                                              File "C:\Users\Monki\AppData\Roaming\Kodi\addons\plugin.program.advanced.emulator.launcher-master\resources\disk_IO.py", line 1061, in fs_load_NFO_file_scanner
                                                file = codecs.open(nfo_file_path, 'rt', 'utf-8')
                                              File "F:\Program Files (x86)\Kodi\system\python\Lib\codecs.py", line 878, in open
                                                file = __builtin__.open(filename, mode, buffering)
                                            ValueError: Invalid mode ('rtb')
                                            -->End of Python script error report<--
```

**Comment by eggfoo** [comment] 2016-07-17 21:17
adding log when  tried to add roms via my HTPC compter


```
 ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.NameError'>
                                            Error Contents: global name 'selectedLauncher' is not defined
                                            Traceback (most recent call last):
                                              File "C:\Users\hteapeac\AppData\Roaming\Kodi\addons\plugin.program.advanced.emulator.launcher-master\addon.py", line 45, in <module>
                                                plugin.run_plugin()
                                              File "C:\Users\hteapeac\AppData\Roaming\Kodi\addons\plugin.program.advanced.emulator.launcher-master\resources\main.py", line 234, in run_plugin
                                                self._command_add_roms(args['launID'][0])
                                              File "C:\Users\hteapeac\AppData\Roaming\Kodi\addons\plugin.program.advanced.emulator.launcher-master\resources\main.py", line 1229, in _command_add_roms
                                                self._roms_add_new_rom(launcher)
                                              File "C:\Users\hteapeac\AppData\Roaming\Kodi\addons\plugin.program.advanced.emulator.launcher-master\resources\main.py", line 3451, in _roms_add_new_rom
                                                thumb_path_noext  = misc_get_thumb_path_noext(selectedLauncher, ROM)
                                            NameError: global name 'selectedLauncher' is not defined
                                            -->End of Python script error report<--
```

**Comment by Wintermute0110** [comment] 2016-07-18 06:50
Thanks. Video is not necessary. First problem is caused when loading an NFO file. Was that NFO gile generated by AEL, or generated by AL or RCB? Since you only have two ROMs, can you put both NFO files in pastebin so I can have a look?

Second issue: I can confirm the bug by looking at the code. Will fix ASAP.

**Comment by Wintermute0110** [comment] 2016-07-18 15:10
Second issue should be fixed in last commit.

**Comment by eggfoo** [comment] 2016-07-18 15:33
Will test fix once home from work & report back

**Comment by eggfoo** [comment] 2016-07-19 15:14
```
> 11:11:29 T:74836   ERROR: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.program.advanced.emulator.launcher/?catID=a8bd32996cc774e02817e0c943fcf25c&com=SHOW_ROMS&launID=05538aae7c638ef914707b130f41222f
> 11:11:29 T:74836   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.program.advanced.emulator.launcher/?catID=a8bd32996cc774e02817e0c943fcf25c&com=SHOW_ROMS&launID=05538aae7c638ef914707b130f41222f) failed
> 11:11:38 T:63268   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
>                                              - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
>                                             Error Type: <type 'exceptions.TypeError'>
>                                             Error Contents: misc_get_thumb_path_noext() takes exactly 3 arguments (2 given)
>                                             Traceback (most recent call last):
>                                               File "C:\Users\Monki\AppData\Roaming\Kodi\addons\plugin.program.advanced.emulator.launcher-master\addon.py", line 45, in <module>
>                                                 plugin.run_plugin()
>                                               File "C:\Users\Monki\AppData\Roaming\Kodi\addons\plugin.program.advanced.emulator.launcher-master\resources\main.py", line 234, in run_plugin
>                                                 self._command_add_roms(args['launID'][0])
>                                               File "C:\Users\Monki\AppData\Roaming\Kodi\addons\plugin.program.advanced.emulator.launcher-master\resources\main.py", line 1229, in _command_add_roms
>                                                 self._roms_add_new_rom(launcher)
>                                               File "C:\Users\Monki\AppData\Roaming\Kodi\addons\plugin.program.advanced.emulator.launcher-master\resources\main.py", line 3449, in _roms_add_new_rom
>                                                 thumb_path_noext  = misc_get_thumb_path_noext(launcher, ROM)
>                                             TypeError: misc_get_thumb_path_noext() takes exactly 3 arguments (2 given)
>                                             -->End of Python script error report<--
> 11:11:44 T:75044   ERROR: XFILE::CDirectory::GetDirectory - Error getting F:\My Documents\Games\video\\Nintendo Wii\extrafanart\
> 11:12:10 T:75172   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
>                                              - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
>                                             Error Type: <type 'exceptions.TypeError'>
>                                             Error Contents: misc_get_thumb_path_noext() takes exactly 3 arguments (2 given)
>                                             Traceback (most recent call last):
>                                               File "C:\Users\Monki\AppData\Roaming\Kodi\addons\plugin.program.advanced.emulator.launcher-master\addon.py", line 45, in <module>
>                                                 plugin.run_plugin()
>                                               File "C:\Users\Monki\AppData\Roaming\Kodi\addons\plugin.program.advanced.emulator.launcher-master\resources\main.py", line 234, in run_plugin
>                                                 self._command_add_roms(args['launID'][0])
>                                               File "C:\Users\Monki\AppData\Roaming\Kodi\addons\plugin.program.advanced.emulator.launcher-master\resources\main.py", line 1229, in _command_add_roms
>                                                 self._roms_add_new_rom(launcher)
>                                               File "C:\Users\Monki\AppData\Roaming\Kodi\addons\plugin.program.advanced.emulator.launcher-master\resources\main.py", line 3449, in _roms_add_new_rom
>                                                 thumb_path_noext  = misc_get_thumb_path_noext(launcher, ROM)
>                                             TypeError: misc_get_thumb_path_noext() takes exactly 3 arguments (2 given)
>                                             -->End of Python script error report<--
```

**Comment by Wintermute0110** [comment] 2016-07-20 06:49
Sorry... That's what happens when you change code without testing. Tonight I will fix and test if I have time.

**Comment by Wintermute0110** [comment] 2016-07-24 16:19
Should be fixed now, and this time I have tested the fix ;)

**Comment by romjacket** [comment] 2016-07-30 08:02
not sure what the problem is, but it looks similar:
using the latest build:```

00:58:44 T:10872  NOTICE: [resources.lib.xbmcswift2b] Request for "/" matches rule for function "index"
00:59:05 T:11140  NOTICE: AEL INFO : _command_add_new_launcher() New launcher type = 0
01:00:16 T:1108   ERROR: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.program.advanced.emulator.launcher/?catID=faf939baf042ad143ab36d52c06b87c7&com=SHOW_ROMS&launID=a9ca5617c3f10ec052e070f392b5b9db
01:00:16 T:1108   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.program.advanced.emulator.launcher/?catID=faf939baf042ad143ab36d52c06b87c7&com=SHOW_ROMS&launID=a9ca5617c3f10ec052e070f392b5b9db) failed
01:00:28 T:9132  NOTICE: AEL INFO : Launcher is empty. No dead ROM check.
01:00:28 T:9132  NOTICE: AEL INFO : Scanning files in G:\Games\Console\Sega Genesis\
01:00:28 T:9132  NOTICE: AEL INFO : Recursive scan activated
01:00:28 T:9132  NOTICE: AEL INFO : Found 559 files
01:00:28 T:9132   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.ValueError'>
                                            Error Contents: Invalid mode ('rtb')
                                            Traceback (most recent call last):
                                              File "C:\Users\romjacket\AppData\Roaming\Kodi\addons\plugin.program.advanced.emulator.launcher-master\addon.py", line 45, in <module>
                                                plugin.run_plugin()
                                              File "C:\Users\romjacket\AppData\Roaming\Kodi\addons\plugin.program.advanced.emulator.launcher-master\resources\main.py", line 236, in run_plugin
                                                self._command_add_roms(args['launID'][0])
                                              File "C:\Users\romjacket\AppData\Roaming\Kodi\addons\plugin.program.advanced.emulator.launcher-master\resources\main.py", line 1231, in _command_add_roms
                                                self._roms_import_roms(launcher)
                                              File "C:\Users\romjacket\AppData\Roaming\Kodi\addons\plugin.program.advanced.emulator.launcher-master\resources\main.py", line 3662, in _roms_import_roms
                                                romdata     = self._roms_process_scanned_ROM(launcherID, ROM)
                                              File "C:\Users\romjacket\AppData\Roaming\Kodi\addons\plugin.program.advanced.emulator.launcher-master\resources\main.py", line 3775, in _roms_process_scanned_ROM
                                                nfo_dic = fs_load_NFO_file_scanner(nfo_file_path)
                                              File "C:\Users\romjacket\AppData\Roaming\Kodi\addons\plugin.program.advanced.emulator.launcher-master\resources\disk_IO.py", line 1061, in fs_load_NFO_file_scanner
                                                file = codecs.open(nfo_file_path, 'rt', 'utf-8')
                                              File "C:\Emulators\Kodi\system\python\Lib\codecs.py", line 878, in open
                                                file = __builtin__.open(filename, mode, buffering)
                                            ValueError: Invalid mode ('rtb')
                                            -->End of Python script error report<--

```

**Comment by Wintermute0110** [comment] 2016-07-30 14:33
Problem happens when opening an NFO file. What Kodi version you have and what OS? Also, please go to AEL settings, advanced, enable debug log and post results. Do not enable debug log in Kodi, just in AEL. Also, if you can put one of your NFO files in pastebin that will help.

**Comment by romjacket** [comment] 2016-07-30 18:59
I have nfo files alongside ROMs in game-folders.
kodi 16.git2016...Windows10:
http://pastebin.com/vzVSwRbD

**Comment by Wintermute0110** [comment] 2016-07-31 05:59
In this last example you did not set recursive scan, so subfolders like G:\Games\Console\Bandai Wonder Swan\Digimon Adventure 02-Tag Tamers where I guess you bat files are were not scanned. No bat file were found so nothing is added to the launcher. I don't see anything strange in this log.

**Comment by romjacket** [comment] 2016-07-31 22:25
sorry about that.  I'll be more careful in sending data this way.  Turning on recursive solved the problem.

here's the log I get when trying to import advanced launcher's  launcher.xml
http://pastebin.com/jhj5H8QX

this is the launchers.xml
http://pastebin.com/NRhtJUrA

**Comment by Wintermute0110** [comment] 2016-08-01 06:13
Las problem importing launchers.xml: That's because an AL hack. On Line 833 you have a forbidden character '&' in the XML. In an standard XML that character must be escaped. AL used a "crafted" XML parser/writer that did not conform to the XML standard (and by the way, was very slow). AEL, however, uses the ElementTree library and that library expects standard XML, hence the exception (error).

I will think on a solution to this.

**Comment by romjacket** [comment] 2016-08-01 06:35
thank you so much for you help in identifying this problem.  Are there other characters which AL doesn't escape which must be in AEL?

**Comment by Wintermute0110** [comment] 2016-08-01 07:22
You have a list here,

http://stackoverflow.com/questions/1091945/what-characters-do-i-need-to-escape-in-xml-documents

In a text editor (if you use windows I recommend Notepad++) search and replace & by &amp; If that's not enought, AEL log will tell you the position (line and column) of the offending characer,

```
Error Type: <class 'xml.etree.ElementTree.ParseError'>
Error Contents: not well-formed (invalid token): line 883, column 32
```

**Comment by Wintermute0110** [comment] 2016-08-01 07:30
Also, NFO file reader/write in AEL does not use ElementTree, is also a "crafted" one. Hence, solving unescaped character problems should be easy. If you can provide one of the offending NFO files I will have a look at it.

**Comment by elwooha6** [comment] 2016-08-02 03:13
I'm having a very similar issue to this, I am on Kodi 17 alpha 3 and AEL 0.9.0. AEL is refusing to load an nfo file that it created itself. Pastebin below

http://pastebin.com/16Sz3yH0

**Comment by Wintermute0110** [comment] 2016-08-02 05:22
@elwooha6 Thanks a lot. I think I found the problem,

http://stackoverflow.com/questions/5941988/print-to-utf-8-encoded-file-with-platform-dependent-newlines

For the same Kodi version, Windows and Linux ship with different Python versions. Error is in an undocumented function call, I just need to change 'rt' by 'r'. For some reason code as it is not works with no problem in Linux but fails in Windows. I will do the hotfix for the NFO files ASAP. However, I will not be able to test it on a Windows machine (but it should work).

**Comment by elwooha6** [comment] 2016-08-02 05:29
Thanks for the quick reply, I can test it on windows no problem and let you know what I find.

**Comment by Wintermute0110** [comment] 2016-08-02 06:06
That's good news. I will commit the fix ASAP.

**Comment by Wintermute0110** [comment] 2016-08-02 14:20
Loading of NFO files should be solved now in Windows. Also, I did some other changes to ensure NFO files are written as UTF-8.

**Comment by eggfoo** [comment] 2016-08-12 01:55
```
21:51:06 T:10044   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.ValueError'>
                                            Error Contents: No JSON object could be decoded
                                            Traceback (most recent call last):
                                              File "C:\Users\hteapeac\AppData\Roaming\Kodi\addons\plugin.program.advanced.emulator.launcher\addon.py", line 45, in <module>
                                                plugin.run_plugin()
                                              File "C:\Users\hteapeac\AppData\Roaming\Kodi\addons\plugin.program.advanced.emulator.launcher\resources\main.py", line 238, in run_plugin
                                                self._command_render_roms(args['catID'][0], args['launID'][0])
                                              File "C:\Users\hteapeac\AppData\Roaming\Kodi\addons\plugin.program.advanced.emulator.launcher\resources\main.py", line 1740, in _command_render_roms
                                                roms = fs_load_ROMs(ROMS_DIR, selectedLauncher['roms_base_noext'])
                                              File "C:\Users\hteapeac\AppData\Roaming\Kodi\addons\plugin.program.advanced.emulator.launcher\resources\disk_IO.py", line 340, in fs_load_ROMs
                                                roms = fs_load_ROMs_JSON(roms_dir, roms_base_noext)
                                              File "C:\Users\hteapeac\AppData\Roaming\Kodi\addons\plugin.program.advanced.emulator.launcher\resources\disk_IO.py", line 558, in fs_load_ROMs_JSON
                                                roms = json.load(file)
                                              File "C:\Program Files (x86)\Kodi\system\python\Lib\json\__init__.py", line 290, in load
                                                **kw)
                                              File "C:\Program Files (x86)\Kodi\system\python\Lib\json\__init__.py", line 338, in loads
                                                return _default_decoder.decode(s)
                                              File "C:\Program Files (x86)\Kodi\system\python\Lib\json\decoder.py", line 366, in decode
                                                obj, end = self.raw_decode(s, idx=_w(s, 0).end())
                                              File "C:\Program Files (x86)\Kodi\system\python\Lib\json\decoder.py", line 384, in raw_decode
                                                raise ValueError("No JSON object could be decoded")
                                            ValueError: No JSON object could be decoded
                                            -->End of Python script error report<--
21:51:06 T:9472   ERROR: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.program.advanced.emulator.launcher/?catID=7afbbc7475e255a5974383cc9366249e&com=SHOW_ROMS&launID=c1a4687e58b689b31886dd49a59e6d48
21:51:06 T:9472   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.program.advanced.emulator.launcher/?catID=7afbbc7475e255a5974383cc9366249e&com=SHOW_ROMS&launID=c1a4687e58b689b31886dd49a59e6d48) failed
```

this is the error it throws up whenever i attempt to enter my nintendo area.

**Comment by eggfoo** [comment] 2016-08-12 01:59
```
21:55:30 T:9472  NOTICE: DVDPlayer: Opening: D:\Arcade\Media\Sony Playstation 2\Video\SoulCalibur II (USA).mp4
21:55:30 T:9472 WARNING: CDVDMessageQueue(player)::Put MSGQ_NOT_INITIALIZED
21:55:30 T:9588  NOTICE: Creating InputStream
21:55:30 T:9588  NOTICE: Creating Demuxer
21:55:30 T:9588  NOTICE: Opening stream: 0 source: 256
21:55:30 T:9588  NOTICE: Creating video codec with codec id: 28
21:55:30 T:9588  NOTICE: CDVDVideoCodecFFmpeg::Open() Using codec: H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10
21:55:30 T:9588  NOTICE: Creating video thread
21:55:30 T:9588  NOTICE: Opening stream: 1 source: 256
21:55:30 T:9588  NOTICE: Finding audio codec for: 86018
21:55:30 T:6008  NOTICE: running thread: video_thread
21:55:30 T:9588  NOTICE: Creating audio thread
21:55:30 T:7372  NOTICE: running thread: CDVDPlayerAudio::Process()
21:55:30 T:6008  NOTICE: CDVDVideoCodecFFmpeg::GetFormat - Creating DXVA(640x480)
21:55:30 T:7372  NOTICE: Creating audio stream (codec id: 86018, channels: 2, sample rate: 48000, no pass-through)
21:55:30 T:7372  NOTICE: CDVDPlayerAudio::OutputPacket duplicate 4 packets of duration 21
21:55:30 T:6008  NOTICE:  fps: 59.940060, pwidth: 640, pheight: 480, dwidth: 640, dheight: 480
21:55:30 T:6008  NOTICE: Display resolution DESKTOP : 2560x1440@ 59.94 - Full Screen (16)
21:55:30 T:6008  NOTICE: D3D: rendering method forced to DXVA processor
21:55:30 T:6008  NOTICE: DXVA::CProcessorHD::InitProcessor - Supported deinterlace methods: Blend:yes, Bob:yes, Adaptive:yes, MoComp:no.
21:55:30 T:7372  NOTICE: CDVDPlayerAudio::OutputPacket duplicate 4 packets of duration 21
21:55:30 T:7372  NOTICE: Previous line repeats 1 times.
21:55:30 T:7372  NOTICE: CDVDPlayerAudio::OutputPacket duplicate 1 packets of duration 21
21:55:30 T:9472 WARNING: CWinRenderer::UpdateVideoFilter - chosen scaling method 1 is not supported by renderer
21:55:30 T:9472 WARNING: CRenderCaptureDX: D3D11_QUERY_OCCLUSION not supported, performance might suffer
21:55:30 T:7372  NOTICE: CDVDPlayerAudio::OutputPacket skipping a packets of duration 21
21:55:34 T:6140  NOTICE: Previous line repeats 1 times.
21:55:34 T:6140   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.KeyError'>
                                            Error Contents: ('romext',)
                                            Traceback (most recent call last):
                                              File "C:\Users\hteapeac\AppData\Roaming\Kodi\addons\plugin.program.advanced.emulator.launcher\addon.py", line 45, in <module>
                                                plugin.run_plugin()
                                              File "C:\Users\hteapeac\AppData\Roaming\Kodi\addons\plugin.program.advanced.emulator.launcher\resources\main.py", line 243, in run_plugin
                                                self._command_edit_rom(args['catID'][0], args['launID'][0], args['romID'][0])
                                              File "C:\Users\hteapeac\AppData\Roaming\Kodi\addons\plugin.program.advanced.emulator.launcher\resources\main.py", line 1381, in _command_edit_rom
                                                romext   = roms[romID]['romext']
                                            KeyError: ('romext',)
                                            -->End of Python script error report<--
```


This is the error i get when i go into my PS2 section, and attempt to edit rom> advanced modifications>Change File  (i used to have my roms are .7z. but converted to .gz File points to .7z, want to point to .gz version)

**Comment by Wintermute0110** [comment] 2016-08-12 05:24
Second problem is easy: I look at the code and identified the error. Will fix ASAP.

First issue is more complicated... it seems that for some reason one launcher has a corrupt JSON file. Can you please make a ZIP file of your ~/.kodi/userdata/addon_data/plugin.program.advanced.emulator.launcher/ directory (recursive ZIP file, including subdirectories) so I can have a look at your launchers and track the problem?

**Comment by eggfoo** [comment] 2016-08-12 11:36
[plugin.program.advanced.emulator.launcher.zip](https://github.com/Wintermute0110/plugin.program.advanced.emulator.launcher/files/415192/plugin.program.advanced.emulator.launcher.zip)


it seems that the "NES" & "nintendo Wii" JSON files are blank?

**Comment by Wintermute0110** [comment] 2016-08-12 13:41
Regarding first issue: you are right, NES and Nintendo Wii ROM JSON databases are 0, which I have never seen in my tests. I cannot tell why this situation happened. In last commit, I made AEL react to this exception so it will treat the case like an empty launcher: you will be able to delete it, edit and rescan the ROMs again. Try to rescan you ROMs in both launcher and if you find strange AEL behaviour report it. I will tell you the exact steps to try to pinpoint the problem.

**Comment by Wintermute0110** [comment] 2016-08-12 13:42
Forgot to say: second issue was easy and should be fixed now.

**Comment by eggfoo** [comment] 2016-08-12 13:54
I'll apply the fix and test when I get home from work. 

Also. I THINK the JSON might have been corrupted from "scanning the rom directory" when adding new Roms. 

I normally manually add Roms. But I think I might have hit scan directory for Roms in error. And they caused the problem?

I'll apply the fix and check/bug test.

**Comment by eggfoo** [comment] 2016-08-12 22:56
So far so good

**Comment by Wintermute0110** [comment] 2016-08-13 07:01
Thanks, that last log is very useful. It is a UnicodeError. However, last part of the log is truncated and I cannot see the line that produces the error. If you can reproduce the bug again and post log that will be very sueful. Make sure the end of the log is like this

```
-->End of Python script error report<--
```

**Comment by eggfoo** [comment] 2016-08-13 12:50
[kodi.txt](https://github.com/Wintermute0110/plugin.program.advanced.emulator.launcher/files/416561/kodi.txt)

**Comment by Wintermute0110** [comment] 2016-08-17 15:29
I already commented on another thread. Did a lot of changes to try to fix the Unicode Errors. Please try last commit and report results.

**Comment by Wintermute0110** [comment] 2016-08-20 13:26
OK, AEL has changed quite a lot now. Lots of new features and stuff. Will close this issue now as it does not make sense (it refers to old stuff that has mostly been replaced by new code).

If you find new problems please open new issues.

**Closed by Wintermute0110** 2016-08-20 13:26 UTC
